// automatically generated by the FlatBuffers compiler, do not modify
export { Feature } from './vector-tile/feature.js';
export { GeomType } from './vector-tile/geom-type.js';
export { Layer } from './vector-tile/layer.js';
export { TagType } from './vector-tile/tag-type.js';
export { Tile } from './vector-tile/tile.js';
