// automatically generated by the FlatBuffers compiler, do not modify
export var TagType;
(function (TagType) {
    TagType[TagType["STRING"] = 0] = "STRING";
    TagType[TagType["FLOAT"] = 1] = "FLOAT";
    TagType[TagType["DOUBLE"] = 2] = "DOUBLE";
    TagType[TagType["INT"] = 3] = "INT";
    TagType[TagType["UINT"] = 4] = "UINT";
    TagType[TagType["SINT"] = 5] = "SINT";
    TagType[TagType["BOOL"] = 6] = "BOOL";
})(TagType || (TagType = {}));
