// automatically generated by the FlatBuffers compiler, do not modify
import * as flatbuffers from 'flatbuffers';
export class Value {
    constructor() {
        this.bb = null;
        this.bb_pos = 0;
    }
    __init(i, bb) {
        this.bb_pos = i;
        this.bb = bb;
        return this;
    }
    static getRootAsValue(bb, obj) {
        return (obj || new Value()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    }
    static getSizePrefixedRootAsValue(bb, obj) {
        bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
        return (obj || new Value()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    }
    stringValue(optionalEncoding) {
        const offset = this.bb.__offset(this.bb_pos, 4);
        return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
    }
    floatValue() {
        const offset = this.bb.__offset(this.bb_pos, 6);
        return offset ? this.bb.readFloat32(this.bb_pos + offset) : 0.0;
    }
    doubleValue() {
        const offset = this.bb.__offset(this.bb_pos, 8);
        return offset ? this.bb.readFloat64(this.bb_pos + offset) : 0.0;
    }
    intValue() {
        const offset = this.bb.__offset(this.bb_pos, 10);
        return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
    }
    uintValue() {
        const offset = this.bb.__offset(this.bb_pos, 12);
        return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
    }
    sintValue() {
        const offset = this.bb.__offset(this.bb_pos, 14);
        return offset ? this.bb.readInt32(this.bb_pos + offset) : 0;
    }
    boolValue() {
        const offset = this.bb.__offset(this.bb_pos, 16);
        return offset ? !!this.bb.readInt8(this.bb_pos + offset) : false;
    }
    static startValue(builder) {
        builder.startObject(7);
    }
    static addStringValue(builder, stringValueOffset) {
        builder.addFieldOffset(0, stringValueOffset, 0);
    }
    static addFloatValue(builder, floatValue) {
        builder.addFieldFloat32(1, floatValue, 0.0);
    }
    static addDoubleValue(builder, doubleValue) {
        builder.addFieldFloat64(2, doubleValue, 0.0);
    }
    static addIntValue(builder, intValue) {
        builder.addFieldInt32(3, intValue, 0);
    }
    static addUintValue(builder, uintValue) {
        builder.addFieldInt32(4, uintValue, 0);
    }
    static addSintValue(builder, sintValue) {
        builder.addFieldInt32(5, sintValue, 0);
    }
    static addBoolValue(builder, boolValue) {
        builder.addFieldInt8(6, +boolValue, +false);
    }
    static endValue(builder) {
        const offset = builder.endObject();
        return offset;
    }
    static createValue(builder, stringValueOffset, floatValue, doubleValue, intValue, uintValue, sintValue, boolValue) {
        Value.startValue(builder);
        Value.addStringValue(builder, stringValueOffset);
        Value.addFloatValue(builder, floatValue);
        Value.addDoubleValue(builder, doubleValue);
        Value.addIntValue(builder, intValue);
        Value.addUintValue(builder, uintValue);
        Value.addSintValue(builder, sintValue);
        Value.addBoolValue(builder, boolValue);
        return Value.endValue(builder);
    }
    unpack() {
        return new ValueT(this.stringValue(), this.floatValue(), this.doubleValue(), this.intValue(), this.uintValue(), this.sintValue(), this.boolValue());
    }
    unpackTo(_o) {
        _o.stringValue = this.stringValue();
        _o.floatValue = this.floatValue();
        _o.doubleValue = this.doubleValue();
        _o.intValue = this.intValue();
        _o.uintValue = this.uintValue();
        _o.sintValue = this.sintValue();
        _o.boolValue = this.boolValue();
    }
}
export class ValueT {
    constructor(stringValue = null, floatValue = 0.0, doubleValue = 0.0, intValue = 0, uintValue = 0, sintValue = 0, boolValue = false) {
        this.stringValue = stringValue;
        this.floatValue = floatValue;
        this.doubleValue = doubleValue;
        this.intValue = intValue;
        this.uintValue = uintValue;
        this.sintValue = sintValue;
        this.boolValue = boolValue;
    }
    pack(builder) {
        const stringValue = (this.stringValue !== null ? builder.createString(this.stringValue) : 0);
        return Value.createValue(builder, stringValue, this.floatValue, this.doubleValue, this.intValue, this.uintValue, this.sintValue, this.boolValue);
    }
}
