# automatically generated by the FlatBuffers compiler, do not modify

# namespace: vector_tile

class TagType(object):
    STRING = 0
    FLOAT = 1
    DOUBLE = 2
    INT = 3
    UINT = 4
    SINT = 5
    BOOL = 6
